# Site settings
title: Raphael Cuba
email: raphael@raphaelcuba.com
description: > #
  Desenvolvimento e arquitetura de software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.raphaelcuba.com" # the base hostname & protocol for your site
twitter_username: raphaelcuba
github_username:  raphaelcuba

# Build settings
markdown: kramdown
